[2024-07-08T02:51:20.569+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-08T02:51:20.706+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Final.create_file_task manual__2024-07-08T02:51:03.487727+00:00 [queued]>
[2024-07-08T02:51:20.774+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Final.create_file_task manual__2024-07-08T02:51:03.487727+00:00 [queued]>
[2024-07-08T02:51:20.775+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-08T02:51:20.864+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): create_file_task> on 2024-07-08 02:51:03.487727+00:00
[2024-07-08T02:51:20.907+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=119) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-08T02:51:20.901+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Final', 'create_file_task', 'manual__2024-07-08T02:51:03.487727+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/dag_test.py', '--cfg-path', '/tmp/tmp737b9yq9']
[2024-07-08T02:51:20.935+0000] {standard_task_runner.py:63} INFO - Started process 121 to run task
[2024-07-08T02:51:20.946+0000] {standard_task_runner.py:91} INFO - Job 21: Subtask create_file_task
[2024-07-08T02:51:21.265+0000] {task_command.py:426} INFO - Running <TaskInstance: Final.create_file_task manual__2024-07-08T02:51:03.487727+00:00 [running]> on host 3b89c1ba7f0f
[2024-07-08T02:51:21.716+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='ha20040204@gmail.com' AIRFLOW_CTX_DAG_OWNER='HA' AIRFLOW_CTX_DAG_ID='Final' AIRFLOW_CTX_TASK_ID='create_file_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-08T02:51:03.487727+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-08T02:51:03.487727+00:00'
[2024-07-08T02:51:21.728+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-08T02:51:21.733+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-08T02:51:21.742+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'touch /opt/***/share_data/database.db']
[2024-07-08T02:51:21.794+0000] {subprocess.py:86} INFO - Output:
[2024-07-08T02:51:21.818+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-07-08T02:51:21.844+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-08T02:51:21.956+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Final, task_id=create_file_task, run_id=manual__2024-07-08T02:51:03.487727+00:00, execution_date=20240708T025103, start_date=20240708T025120, end_date=20240708T025121
[2024-07-08T02:51:22.033+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-08T02:51:22.057+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
