[2024-07-07T12:29:09.170+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-07T12:29:09.207+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Final_exam.create_file_task manual__2024-07-07T12:25:12.941684+00:00 [queued]>
[2024-07-07T12:29:09.220+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Final_exam.create_file_task manual__2024-07-07T12:25:12.941684+00:00 [queued]>
[2024-07-07T12:29:09.221+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-07T12:29:09.244+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): create_file_task> on 2024-07-07 12:25:12.941684+00:00
[2024-07-07T12:29:09.253+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=59) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-07T12:29:09.255+0000] {standard_task_runner.py:63} INFO - Started process 63 to run task
[2024-07-07T12:29:09.256+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Final_exam', 'create_file_task', 'manual__2024-07-07T12:25:12.941684+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp3f_auz9a']
[2024-07-07T12:29:09.258+0000] {standard_task_runner.py:91} INFO - Job 104: Subtask create_file_task
[2024-07-07T12:29:09.328+0000] {task_command.py:426} INFO - Running <TaskInstance: Final_exam.create_file_task manual__2024-07-07T12:25:12.941684+00:00 [running]> on host 09841d3968a1
[2024-07-07T12:29:09.457+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='ha20040204@gmail.com' AIRFLOW_CTX_DAG_OWNER='HA' AIRFLOW_CTX_DAG_ID='Final_exam' AIRFLOW_CTX_TASK_ID='create_file_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-07T12:25:12.941684+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-07T12:25:12.941684+00:00'
[2024-07-07T12:29:09.459+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-07T12:29:09.460+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-07T12:29:09.461+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'touch /opt/***/dags/database.db']
[2024-07-07T12:29:09.474+0000] {subprocess.py:86} INFO - Output:
[2024-07-07T12:29:09.481+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-07-07T12:29:09.482+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-07T12:29:09.515+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Final_exam, task_id=create_file_task, run_id=manual__2024-07-07T12:25:12.941684+00:00, execution_date=20240707T122512, start_date=20240707T122909, end_date=20240707T122909
[2024-07-07T12:29:09.550+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-07T12:29:09.585+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-07T12:29:09.588+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
