[2024-07-10T04:29:00.955+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-10T04:29:00.997+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Final.starting scheduled__2024-07-10T04:27:00+00:00 [queued]>
[2024-07-10T04:29:01.011+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Final.starting scheduled__2024-07-10T04:27:00+00:00 [queued]>
[2024-07-10T04:29:01.012+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-10T04:29:01.045+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): starting> on 2024-07-10 04:27:00+00:00
[2024-07-10T04:29:01.059+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=55) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-10T04:29:01.062+0000] {standard_task_runner.py:63} INFO - Started process 57 to run task
[2024-07-10T04:29:01.063+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Final', 'starting', 'scheduled__2024-07-10T04:27:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/dag_test.py', '--cfg-path', '/tmp/tmptuvna7mt']
[2024-07-10T04:29:01.065+0000] {standard_task_runner.py:91} INFO - Job 28: Subtask starting
[2024-07-10T04:29:01.222+0000] {task_command.py:426} INFO - Running <TaskInstance: Final.starting scheduled__2024-07-10T04:27:00+00:00 [running]> on host dd74537ce0b1
[2024-07-10T04:29:01.475+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='ha20040204@gmail.com' AIRFLOW_CTX_DAG_OWNER='HA' AIRFLOW_CTX_DAG_ID='Final' AIRFLOW_CTX_TASK_ID='starting' AIRFLOW_CTX_EXECUTION_DATE='2024-07-10T04:27:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-10T04:27:00+00:00'
[2024-07-10T04:29:01.477+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-10T04:29:01.480+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-10T04:29:01.482+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "Chuẩn bị cào dữ liệu"']
[2024-07-10T04:29:01.499+0000] {subprocess.py:86} INFO - Output:
[2024-07-10T04:29:01.502+0000] {subprocess.py:93} INFO - Chuẩn bị cào dữ liệu
[2024-07-10T04:29:01.503+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-07-10T04:29:01.504+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-10T04:29:01.550+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Final, task_id=starting, run_id=scheduled__2024-07-10T04:27:00+00:00, execution_date=20240710T042700, start_date=20240710T042900, end_date=20240710T042901
[2024-07-10T04:29:01.607+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-10T04:29:01.680+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-10T04:29:01.686+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
